import React from 'react';
import { AGL_IMAGES, AglImageName } from '../data/aglImages';
import './ResponsiveImage.css';

interface ResponsiveImageProps {
  /** Image slot from src/data/aglImages.ts (generated by scripts/optimize-images.mjs). */
  name: AglImageName;
  alt: string;
  /** Optional art-directed image for narrow screens (e.g. a portrait hero on phones). */
  mobileName?: AglImageName;
  /** Heroes / above-the-fold images: load immediately with high priority. Default: lazy. */
  eager?: boolean;
  /** Rendered width hint for the browser, e.g. "(max-width: 768px) 100vw, 33vw". */
  sizes?: string;
  className?: string;
  imgClassName?: string;
}

const MOBILE_QUERY = '(max-width: 767px)';

function srcSet(name: AglImageName, ext: 'webp' | 'jpg'): string {
  return AGL_IMAGES[name].widths.map(w => `/images/agl/${name}-${w}.${ext} ${w}w`).join(', ');
}

function largest(name: AglImageName): number {
  const { widths } = AGL_IMAGES[name];
  return widths[widths.length - 1];
}

/**
 * <picture> with WebP + JPG fallbacks at every generated width. Explicit width/height come from
 * the manifest so the browser reserves the right space before the image loads (no layout shift).
 */
export const ResponsiveImage: React.FC<ResponsiveImageProps> = ({
  name,
  alt,
  mobileName,
  eager = false,
  sizes = '100vw',
  className = '',
  imgClassName = '',
}) => {
  const info = AGL_IMAGES[name];
  // React 18 doesn't know the fetchPriority prop yet, so pass the raw attribute.
  const priority = eager ? { fetchpriority: 'high' } : {};

  return (
    <picture className={`agl-responsive-picture ${className}`.trim()}>
      {mobileName && (
        <>
          <source media={MOBILE_QUERY} type="image/webp" srcSet={srcSet(mobileName, 'webp')} sizes={sizes} />
          <source media={MOBILE_QUERY} type="image/jpeg" srcSet={srcSet(mobileName, 'jpg')} sizes={sizes} />
        </>
      )}
      <source type="image/webp" srcSet={srcSet(name, 'webp')} sizes={sizes} />
      <img
        className={`agl-responsive-image ${imgClassName}`.trim()}
        src={`/images/agl/${name}-${largest(name)}.jpg`}
        srcSet={srcSet(name, 'jpg')}
        sizes={sizes}
        width={info.width}
        height={info.height}
        alt={alt}
        loading={eager ? 'eager' : 'lazy'}
        decoding={eager ? 'sync' : 'async'}
        {...priority}
      />
    </picture>
  );
};
